<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="sayan-Vostro-3558" failures="1" tests="6" name="Default test" time="71.264" errors="0" timestamp="2024-09-19T17:40:37 IST">
  <testcase classname="SeleniumTestNgMavenFramework.BasicAuthTest" name="TC_VerifyLoginTitlePage" time="4.496"/>
  <testcase classname="SeleniumTestNgMavenFramework.BasicAuthTest" name="TC_LoginWithoutEmail" time="7.557"/>
  <testcase classname="SeleniumTestNgMavenFramework.BasicAuthTest" name="TC_LoginWithoutPassword" time="4.988"/>
  <testcase classname="SeleniumTestNgMavenFramework.BasicAuthTest" name="TC_LoginWithWrongEmail" time="5.716"/>
  <testcase classname="SeleniumTestNgMavenFramework.BasicAuthTest" name="TC_LoginWithWrongPassword" time="5.969"/>
  <testcase classname="SeleniumTestNgMavenFramework.BasicAuthTest" name="TC_LoginWithValidCredential" time="21.392">
    <failure type="java.lang.AssertionError" message="❌ Element not exist. (waitForElementPresent) By.xpath: //h2[normalize-space()=&amp;apos;Home&amp;apos;]">
      <![CDATA[java.lang.AssertionError: ❌ Element not exist. (waitForElementPresent) By.xpath: //h2[normalize-space()='Home']
at org.testng.Assert.fail(Assert.java:99)
at helpers.WebUI.waitForElementPresent(WebUI.java:478)
at helpers.WebUI.waitForElementVisible(WebUI.java:424)
at pageObjects.BasicAuthPage.loginSuccessWithValidCredentials(BasicAuthPage.java:69)
at SeleniumTestNgMavenFramework.BasicAuthTest.TC_LoginWithValidCredential(BasicAuthTest.java:40)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- TC_LoginWithValidCredential -->
</testsuite> <!-- Default test -->
